[package]
name = "qsv"
version = "0.17.3"  #:version
authors = ["Joel Natividad <joel@datHere.com>"]
description = "A high performance CSV command line toolkit."
documentation = "https://docs.rs/crate/qsv"
homepage = "https://github.com/jqnatividad/qsv"
repository = "https://github.com/jqnatividad/qsv"
readme = "README.md"
keywords = ["csv", "geocode", "slice", "cli", "opendata"]
license = "Unlicense/MIT"
autotests = false
edition = "2018"
exclude = ["*.zip"]

[[bin]]
name = "qsv"
test = false
bench = false
doctest = false

[[test]]
name = "tests"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = false

[profile.test]
opt-level = 3

[dependencies]
mimalloc = { version = "0.1.26", default-features = false }
byteorder = "1.4"
crossbeam-channel = "0.5"
csv = "1.1"
csv-index = "0.1"
docopt = "1"
filetime = "0.2"
hlua = "0.4.1"
num_cpus = "1"
rand = "0.7"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
qsv-stats = "0.3"
tabwriter = "1.2"
threadpool = "1.8"
chrono = "0.4"
dateparser = "0.1.6"
lazy_static = "1"
reverse_geocoder = "2"
currency = "0.4"
itertools = "0.10"
uuid = { version = "0.8.1", features = ["v4"] }
log = "0.4.14"
log4rs = "1.0.0"

[build-dependencies]
rustc_version = "0.4"

[dev-dependencies]
quickcheck = { version = "0.9", default-features = false }
log = "0.4"
