name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome! Bear in mind that issues should be used primarily for bug reports, and for tracking existing work in the Backlog. Use Discussions for help on Usage, Ideas, and general comments.'
        pr-message: 'Awesome! Thanks for creating your first qsv PR. Please be sure to run `rustfmt` (cargo fmt) and `clippy` (cargo clippy) so we can standardize the code.'
