name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Update Rust
      run: rustup update
    - name: Setup Rust-cache
      uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --verbose --locked --all-features
    - name: Run tests
      run: cargo test --verbose --locked --all-features
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Clippy Check
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
